// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	city "github.com/nofendian17/openota/apigw/internal/delivery/rest/model/request/city"

	mock "github.com/stretchr/testify/mock"

	responsecity "github.com/nofendian17/openota/apigw/internal/delivery/rest/model/response/city"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *UseCase) Create(ctx context.Context, _a1 city.Create) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, city.Create) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, ID
func (_m *UseCase) Delete(ctx context.Context, ID string) error {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *UseCase) GetAll(ctx context.Context) ([]*responsecity.City, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*responsecity.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*responsecity.City, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*responsecity.City); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*responsecity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, ID
func (_m *UseCase) GetByID(ctx context.Context, ID string) (*responsecity.City, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *responsecity.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*responsecity.City, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *responsecity.City); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responsecity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByStateID provides a mock function with given fields: ctx, stateID
func (_m *UseCase) GetByStateID(ctx context.Context, stateID string) ([]*responsecity.City, error) {
	ret := _m.Called(ctx, stateID)

	if len(ret) == 0 {
		panic("no return value specified for GetByStateID")
	}

	var r0 []*responsecity.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*responsecity.City, error)); ok {
		return rf(ctx, stateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*responsecity.City); ok {
		r0 = rf(ctx, stateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*responsecity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, stateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, ID, _a2
func (_m *UseCase) Update(ctx context.Context, ID string, _a2 city.Update) error {
	ret := _m.Called(ctx, ID, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, city.Update) error); ok {
		r0 = rf(ctx, ID, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
