// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"
	response "github.com/nofendian17/openota/apigw/internal/delivery/rest/model/response/country"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// GetByCode provides a mock function with given fields: ctx, Code
func (_m *UseCase) GetByCode(ctx context.Context, Code string) (*response.Country, error) {
	ret := _m.Called(ctx, Code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *response.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.Country, error)); ok {
		return rf(ctx, Code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.Country); ok {
		r0 = rf(ctx, Code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, Code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, ID
func (_m *UseCase) GetByID(ctx context.Context, ID string) (*response.Country, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *response.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.Country, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.Country); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
