// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	country "github.com/nofendian17/openota/apigw/internal/delivery/rest/model/request/country"
	mock "github.com/stretchr/testify/mock"

	responsecountry "github.com/nofendian17/openota/apigw/internal/delivery/rest/model/response/country"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *UseCase) Create(ctx context.Context, _a1 country.Create) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, country.Create) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *UseCase) GetAll(ctx context.Context) ([]*responsecountry.Country, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*responsecountry.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*responsecountry.Country, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*responsecountry.Country); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*responsecountry.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCode provides a mock function with given fields: ctx, Code
func (_m *UseCase) GetByCode(ctx context.Context, Code string) (*responsecountry.Country, error) {
	ret := _m.Called(ctx, Code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *responsecountry.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*responsecountry.Country, error)); ok {
		return rf(ctx, Code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *responsecountry.Country); ok {
		r0 = rf(ctx, Code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responsecountry.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, Code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, ID
func (_m *UseCase) GetByID(ctx context.Context, ID string) (*responsecountry.Country, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *responsecountry.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*responsecountry.Country, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *responsecountry.Country); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responsecountry.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
