// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Responder is an autogenerated mock type for the Responder type
type Responder struct {
	mock.Mock
}

// Json provides a mock function with given fields: w, statusCode
func (_m *Responder) Json(w http.ResponseWriter, statusCode int) {
	_m.Called(w, statusCode)
}

// NewResponder creates a new instance of Responder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResponder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Responder {
	mock := &Responder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
