application:
  name: "MyApp"
  version: "1.0.0"
  address: "localhost"
  port: 3000
database:
  driver: "mysql" # "mysql" or "postgres" or "sqlite" or "sqlserver"
  host: "localhost"
  port: 3306
  username: "root"
  password: "Password123"
  database: "test"
  charset: "utf8mb4"
  timezone: "Asia/Jakarta"
  maxIdleConns: 10
  maxOpenConns: 100
  sslMode: false
  debug: true
  disableMetric: true
  disableTrace: true
cache:
  host: "localhost"
  port: 6379
  username: ""
  password: ""
  database: 0
logger:
  output: json # text or json
  level: debug # info or warn or debug or error